Feat: Added a pre-commit hook; Closes: #1075
bytedeck/bytedeck pull request #1098
Opened 2022-07-20 04:23 UTC by 9921622

2022-07-20 04:39 UTC, tylerecouture requested changes
Missing requirement from issue: use .flake8 for config.

Also, can you update the README with a line on how to "install" the pre-commit hook? does it need to be installed somehow or registered with a new development environment or does it kick in automatically? Not sure how git would know about it unless it was registered somehow?

2022-07-20 04:39 UTC, tylerecouture commented on .pre-commit-config.yaml
> +            args: [
can you use the existing .flake8 file instead of duplicating args here?  otherwise need to always remember to update in two locations.

2022-07-20 04:43 UTC, tylerecouture commented on .pre-commit-config.yaml
> +            args: [
Readme on how to install... or auto install it:
https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

2022-07-21 01:33 UTC, 9921622 commented
Pretty sure it works now.

For old existing + new repositories you just need to re init git with `git init --template=.git-template`

2022-07-21 03:28 UTC, merged