WIP: implement Safe & Advanced SummernoteWidget(s)
bytedeck/bytedeck pull request #1328
Opened 2023-04-10 05:09 UTC by bashu

### What?

I've implemented `ByteDeckSummernoteSafeWidget` and `ByteDeckSummernoteAdvancedWidget` classes as substitute for widgets from `django-summernote` package.

### Why?

See https://github.com/bytedeck/bytedeck/issues/1302

### How?

append `bytedeck_summernote` right after `django_summernote` in INSTALLED_APPS
```python
INSTALLED_APPS = [
...
'django_summernote',
'bytedeck_summernote',
]
```

update urls.py, replace `django_summernote.urls` with `bytedeck_summernote.urls`:

```python
urlpatterns += [
...
    # bytedeck summernote
    url(r'^summernote/', include('bytedeck_summernote.urls')),
]
```

Replace imports:
```python
from django_summernote.widgets import SummernoteInplaceWidget, SummernoteWidget

# and
from django_summernote.admin import SummernoteModelAdmin, SummernoteInlineModelAdmin
```
with

```python
from bytedeck_summernote.widgets import ByteDeckSummernoteSafeWidget, ByteDeckSummernoteAdvancedWidget

# and
from bytedeck_summernote.admin import ByteDeckSummernoteModelAdmin, ByteDeckSummernoteInlineModelAdmin

```

### Testing?
Yes
### Screenshots (if front end is affected)

![summernoteinplacewidget](https://user-images.githubusercontent.com/144783/227222795-4dd2477a-2ae1-4d0f-a439-e672fc79dd67.gif)

### Anything Else?

Q: Why there are a lot of templates?
A: To avoid clashing with django_summernote stock templates

Q: What was changed there?
A: Either "include" or "extends" tags, and two lines of code in "widget_common.html" file

Q: Why did you copy-pasted `render` methods of widget classes?
A: Because original developers hardcoded template names, instead of using easy to override "template_name" attribute.

Q: Why all classes has prefix "ByteDeck" ?
A: To avoid confusion with stock `django_summernote`, but please suggest better prefixes.

2023-04-10 15:30 UTC, tylerecouture requested changes
This is looking great.  I will test out a live version of this when I get a chance.  For now a question for you. My biggest concern is the sustainability of the code.  What happens when django-summernote updates?  What is the workflow for keeping our hacked version up to date?  You've got the changes well documented now, so perhaps that's all we need.

Would it make more sense for use to move your work into a fork of the actual Summernote widget? It seems like that would be easier to maintain, since the code will maintain it's connection via git to the upstream repo.  Then we could also suggest PRs to the original as well, reducing our delta from the upstream.  However I'm not sure how we install a fork in the app?

I'm asking for your professional advice on this.

2023-04-10 15:32 UTC, tylerecouture commented on src/quest_manager/forms.py
> +            'submission_details': ByteDeckSummernoteSafeWidget(),
`instructions` and `submission_details` fields should both use the AdvancedWidget

2023-04-10 15:35 UTC, tylerecouture commented on src/bytedeck_summernote/widgets.py
> +class ByteDeckSummernoteAdvancedWidget(SummernoteWidget):
Docstring needed for this class describing the purpose of the AdvancedWidget (what does it add/change from it's base class?)

2023-04-10 15:36 UTC, tylerecouture commented on src/bytedeck_summernote/widgets.py
> +class ByteDeckSummernoteSafeWidget(SummernoteInplaceWidget):
Docstring needed for this class describing the purpose of the SafeWidget (what does it add/change from it's base class?)

2023-04-10 15:39 UTC, tylerecouture commented on src/utilities/forms.py
> +            'content': ByteDeckSummernoteSafeWidget(),
This can use AdvancedWidget

2023-04-11 08:08 UTC, bashu commented
> This is looking great. I will test out a live version of this when I get a chance. For now a question for you. My biggest concern is the sustainability of the code. What happens when django-summernote updates? What is the workflow for keeping our hacked version up to date? You've got the changes well documented now, so perhaps that's all we need.

See my latest commits, I tried to resolve it. In a near future all you need to is:

a) if this one got fixed https://github.com/summernote/django-summernote/issues/465, then replace its content of `bytecode_summernote/widget_commont.html` with:
```html+django
{% extends "django_common/widget_common.html" %}
```

b) pin newer version in `requirements.txt` and until there are no backward incompatibilities in django-summernote nor with django itself, thats all you need.

> Would it make more sense for use to move your work into a fork of the actual Summernote widget? It seems like that would be easier to maintain, since the code will maintain it's connection via git to the upstream repo. Then we could also suggest PRs to the original as well, reducing our delta from the upstream. However I'm not sure how we install a fork in the app?

with my latest patches, there are no benefits to maintain separate fork. However if we manage to accept some of our changes (templates and more generic implementation of admin+widgets classes) into upstream version of `django_summernote`, then we can reduce "bytedeck's" specific implementatin to three-five lines of code.

2023-04-11 08:27 UTC, bashu commented
to @tylerecouture and @yujinyuz once again tests fail, and once again it's unrelated to this Pull Request.

2023-04-11 12:34 UTC, tylerecouture commented
> TODO: What is the workflow for keeping our hacked version up to date? 
>  
> a) if this one got fixed [summernote/django-summernote#465](https://github.com/summernote/django-summernote/issues/465), then replace the content of `bytecode_summernote/widget_common.html` file with:
> 
> ```
> {% extends "django_common/widget_common.html" %}
> ```
> 
> yes, one line of code instead of hundred and half
> 
> b) pin newer version in `requirements.txt` and until there are no backward incompatibilities in django-summernote nor in django itself, that's all you need.
> 
> with my latest patches, there are no benefits to maintain separate fork. However if we manage to accept some of our changes (templates and more generic implementation of admin+widgets classes) into upstream version of `django_summernote`, then we can reduce "bytedeck" specific implementation to three-five lines of code.

Excellent.  Can you paste the above content into one of the docstrings or a block comment at the top?  Whatever location you think is most obvious.

2023-04-11 12:35 UTC, bashu commented
> @bashu This looks related? All three test failures have this same error:

this happened after I triggered "github actions" with forced push, after my last comment. Yeah they are related, but again in happens only on github, works normally on my machine, to @yujinyuz any ideas how to solve it?

2023-04-11 12:50 UTC, bashu commented
to @tylerecouture how about README.md, will be automatically rendered by github as index.html when you navigate the folder, see

![Screenshot 2023-04-11 at 6 48 57 PM](https://user-images.githubusercontent.com/144783/231167386-57045684-9607-43ad-9401-a3300914736f.png)

2023-04-11 13:39 UTC, tylerecouture requested changes
I'm not sure if those are why the tests are failing, or maybe you're missing a migration?

2023-04-11 13:39 UTC, tylerecouture commented on src/portfolios/forms.py
> +            'description': ByteDeckSummernoteSafeWidget(),
ByteDeckSummernoteSafeInplaceWidget?

2023-04-11 13:50 UTC, tylerecouture commented
> > @bashu This looks related? All three test failures have this same error:
> 
> this happened after I triggered "github actions" with forced push, after my last comment. Yeah they are related, but again it happens only on github, works normally on my machine, to @yujinyuz any ideas how to solve it?

Try it with an empty database, that's the only difference between github actions and local testing.  Last feature, you were trying to access the db when the app loads, and I suspect it's the same issue here.  You need to lazy load things or access after migrations.

2023-04-11 14:03 UTC, bashu commented on src/announcements/forms.py
> +            'content': ByteDeckSummernoteSafeWidget(),
was it fixed by later commits, no?

2023-04-11 14:03 UTC, bashu commented on src/portfolios/forms.py
> +            'description': ByteDeckSummernoteSafeWidget(),
see above

2023-04-11 14:45 UTC, tylerecouture commented on src/portfolios/forms.py
> +            'description': ByteDeckSummernoteSafeWidget(),
This is current code on github,

2023-04-11 15:27 UTC, bashu commented on src/portfolios/forms.py
> +            'description': ByteDeckSummernoteSafeWidget(),
fixed

2023-04-12 05:52 UTC, bashu commented
to @tylerecouture the problem with test in "notifications" module,

if you run this:
```
docker-compose run web bash -c "python ./src/manage.py test src/bytedeck_summernote src/notifications --parallel --failfast"
```
tests fill fail, but if you test in different order like this:
```
docker-compose run web bash -c "python ./src/manage.py test src/notifications src/bytedeck_summernote --parallel --failfast"
```

everything is working

2023-04-12 07:35 UTC, bashu commented
> Can you run tests locally with an empty database and ensure you aren't trying to access the db before migrations run? That was a problem with the GFK widget at one point

this thing again:
```python
======================================================================
FAIL: test_active (quest_manager.tests.test_models.QuestTestModel)
The active method of the Quest model's parent "XPItem" should return the correct values based on a quest object's settings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/src/quest_manager/tests/test_models.py", line 161, in test_active
    self.assertEqual(Quest.objects.get(name="past-time-quest").active, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 645 tests in 1330.235s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

2023-04-13 01:35 UTC, tylerecouture requested changes
Everything is looking great!  You just have one method that isn't tested.  Can you cover that and then we should be done!!!

![image](https://user-images.githubusercontent.com/10604391/231623340-551bebe1-81c9-404a-a1ab-1de85cef64fc.png)

2023-04-13 02:26 UTC, tylerecouture commented
Do you know why scripts run twice when you load an form in Django Admin?

For example, put `<script>alert("hello")</script>` in an advanced widget in Django Admin, save, then load the form.  You get two popups.

2023-04-13 02:45 UTC, merged

2023-04-13 04:09 UTC, bashu commented
> Everything is looking great! You just have one method that isn't tested. Can you cover that and then we should be done!!!

I see it already fixed by @TimberlineHackerspace

2023-04-13 04:44 UTC, bashu commented on src/bytedeck_summernote/templates/bytedeck_summernote/widget_iframe.html
please look into thin PR https://github.com/bytedeck/bytedeck/pull/1335 it answers your question

2023-04-13 06:54 UTC, bashu commented
> Do you know why scripts run twice when you load a form in Django Admin?
> 
> For example, put `<script>alert("hello")</script>` in an advanced widget in Django Admin, save, then load the form. You get two popups.

Can confirm, will fix it https://github.com/bytedeck/bytedeck/issues/1336

2023-04-13 10:56 UTC, tylerecouture commented
> > Everything is looking great! You just have one method that isn't tested. Can you cover that and then we should be done!!!
> 
> I see it already fixed by @TimberlineHackerspace

That is me from a different computer =)