WIP: Refactoring of quest list using bootstrap-table
bytedeck/bytedeck pull request #1372
Opened 2023-05-23 19:06 UTC by Enprogames

### What?
I've made a first attempt at refactoring the quest list to be a bootstrap-table.
### Why?
Once this is working properly, it will allow more dynamic actions to be performed on the lists of quests, such as sorting, filtering, etc. See #1369.
### How?
I updated `quests2.html` to match `quests.html`, and made it point to `tab_quests_available2.html`. This gives this code a place to live while it is still a work in progress.

Most of the work on this issue was done inside of `tab_quests_available2.html`. The code mostly matches [this JSFiddle Example](https://jsfiddle.net/enprogames/cv8f2Lgh/36/), but with additional complexity. So essentially, JavaScript code was added to do the following:
- Initializing the Bootstrap Table
- Adding the content to the hidden divs
- Expanding the row when it is clicked, and collapsing any other expanded rows
- Collapsing the row when it is clicked again

Somewhere else (I'm not sure where), there is JavaScript that is responsible for:
- Adding "active" and "collapse" classes to rows when they are expanded or collapsed
### Testing?
N/A
### Screenshots (if front end is affected)
![image](https://github.com/bytedeck/bytedeck/assets/11304586/fa7e7a86-3a2c-40fd-bb47-7fd9690c3aab)

### Anything Else?
There are still a few problems with it that need to be addressed:
- Currently, all of the CSS and JavaScript code for this exists inside of `tab_quests_available2.html`. This is because it made it easier to work on, and because I wasn't sure which other files to put these in. This should be fixed soon.
- Expanded quests don’t have blue highlight. These CSS rules aren’t being applied properly.
- The quest list table doesn’t have the same styling as the old version. The styling here has several moving parts and is quite complex, so making it look like the old one would be a big undertaking.
- Upon expanding the first quest, the loading prompt doesn’t go away unless you collapse/expand it again. It looks like the HTML content isn’t being inserted and updated as it should be?
- I can't figure out where the JavaScript code exists that was making the old collapsing functionality work, but it is still affecting these changes in a wonky way. So either this new code or that old code will need to be refactored.
### Review request
@tylerecouture

2023-05-24 20:40 UTC, tylerecouture commented on src/quest_manager/templates/quest_manager/tab_quests_available2.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.18.3/bootstrap-table.min.js"></script>
@Enprogames See if you can add the full integrity check for this js import

2023-05-24 21:24 UTC, tylerecouture commented
Code is broken, so I can't take a closer look, but some initial comments:

> Currently, all of the CSS and JavaScript code for this exists inside of tab_quests_available2.html. This is because it made it easier to work on, and because I wasn't sure which other files to put these in. This should be fixed soon.

I would put these into their own `bootstrap-table-accordian.css|.js` files within `quest_manager/static/css|js`

> Expanded quests don’t have blue highlight. These CSS rules aren’t being applied properly.

> The quest list table doesn’t have the same styling as the old version. The styling here has several moving parts and is quite complex, so making it look like the old one would be a big undertaking.

Styling doesn't have to match exactly, it just needs to look clean, and good.  Start by giving the table element the classes .table and .table-hover

See https://getbootstrap.com/docs/3.3/css/#tables

>Upon expanding the first quest, the loading prompt doesn’t go away unless you collapse/expand it again. It looks like the HTML content isn’t being inserted and updated as it should be?

See `ajax_content_loading.html`

> I can't figure out where the JavaScript code exists that was making the old collapsing functionality work, but it is still affecting these changes in a wonky way. So either this new code or that old code will need to be refactored.

Current accordions use Bootstrap built in accordion that is triggered by css classes and ids. See here:
https://getbootstrap.com/docs/3.3/javascript/#collapse-example-accordion

2023-05-25 03:40 UTC, tylerecouture reviewed
Great progress.  Request my review again when you'd like me to take another look.

2023-05-25 03:40 UTC, tylerecouture requested changes
As discussed.

2023-05-30 06:16 UTC, tylerecouture requested changes
Haven't dug into the code yet, just played around with the changes in a browser, and it is looking awesome!!  A few things to tweak:
1.  Mobile view is messed up, I think because the table headings aren't set to disappear, only the table columns, so left with some broken layout in mobile/narrow screen:
![image](https://github.com/bytedeck/bytedeck/assets/10604391/95bdfc6a-d695-4caa-b505-8a4b95be6836)

2. The text is smaller (e.g. 14pt  vs 16pt in the old version for the quest title)

3. Column alignment is funky, compared to old version (I know the sorting arrows mess it all up a bit, but maybe align the headings to right and align the XP and campaign content to center?  Try a few things to make it look better:
![image](https://github.com/bytedeck/bytedeck/assets/10604391/4595d270-2d9d-47d6-a8fb-798518f691b2)

4. Add the Search!  This should just be a simple data attribute in the bootstrap-table, see the students or tags list tables for an example. `data-search='true'`

2023-05-30 06:34 UTC, tylerecouture commented
@Enprogames Also, please make this change: replace the expiry and last column (where the status icons appear) with a single column: Tags (which should use the `{{config.custom_name_for_tag }}` or whatever that field is called.

Then, for the column content for each quest, put a comma separate list of tags, I think `{{q.tags.all|join:", "}}`

You can also now replace the old code with your new stuff (don't delete the old ones yet though, please just rename them all with suffix _old and maybee provide access to it via url `/available/old` or something like that

2023-05-31 00:02 UTC, Enprogames commented
> @Enprogames Also, please make this change: replace the expiry column and all its logic witha column to show tags instead: Tags (which should use the `{{config.custom_name_for_tag }}` or whatever that field is called).
> 
> Then, for the column content for each quest, put a comma separate list of tags, I think `{{q.tags.all|join:", "}}`
> 
> You can also now replace the old code with your new stuff (don't delete the old ones yet though, please just rename them all with suffix _old and maybee provide access to it via url `/available/old` or something like that

- [x] Add search field
- [x] Increase text size to 16px
- [x] Replace expiry column with custom tags
- [x] Make this the official quest_available view
- [ ] Fix column alignment
- [ ] Fix broken mobile view:
    - This is proving to be quite difficult. The bootstrap and bootstrap-table documentations don't seem to have any good instructions on this. [It seems like the only straightforward way is to use `@media` CSS tags](https://stackoverflow.com/a/42534400/6946463)? I will try this soon.

2023-05-31 02:07 UTC, merged