Refactor create_noticiation_tasks
bytedeck/bytedeck pull request #1511
Opened 2023-10-29 06:40 UTC by yujinyuz

### What?

Refactor creating notification tasks

Resolves #1510 

### Why?

The current implementation has a problem since the `create_notification_tasks` gets run if the app is redeployed. Meaning, newly created tenants won't have that daily task in their periodic task queue.

### How?

By using the dispatcher pattern recommended by `tenant-scheams-celery`, it will loop through all tenants regularly based on the cron schedule instead of creating the task whenever the`create_notification_tasks` is called

### Testing?
### Screenshots (if front end is affected)
### Anything Else?
### Review request
@tylerecouture

2023-11-06 04:19 UTC, tylerecouture requested changes
Typo and method name improvement.

2023-11-06 04:19 UTC, tylerecouture commented on src/hackerspace_online/celery.py
> +    "Send daily email of noticiations to all schemas": {
Typo in notifications

2023-11-06 04:19 UTC, tylerecouture commented on src/hackerspace_online/celery.py
>          "task": "profile_manager.tasks.invalidate_profile_cache_in_all_schemas",
I know this was a previous PR, but this needs a better name.  We do not cache profiles, so we are not invalidating profile caches.  What does this method actually do? it should be named to match what it's doing.

2023-11-12 23:19 UTC, tylerecouture commented
@yujinyuz have the comments been resolved? If so, please reply to each and mark as resolved.

2023-11-18 03:56 UTC, yujinyuz commented
@tylerecouture done.

Does the new description/method name look better?

2023-11-26 07:14 UTC, merged