Upgrade django
bytedeck/bytedeck pull request #907
Opened 2022-01-28 10:06 UTC by yujinyuz

Closes #903

2022-01-28 11:10 UTC, yujinyuz commented
I was able to narrow down the issue that `django-tenants==3.1.0` doesn't break the tests while `django-tenants==3.4.2` does.

I'll need to dig more into this

2022-01-28 12:10 UTC, yujinyuz commented
I tried to search for other tests that use `save_model` but it seems that this is an unreliable way to test validators.

Based on django's [documentation](https://docs.djangoproject.com/en/3.2/ref/validators/#how-validators-are-run)

> Note that validators will not be run automatically when you save a model, but if you are using a ModelForm, it will run your validators on any fields that are included in your form. See the ModelForm documentation for information on how model validation interacts with forms.

I'm not sure why it was working before though...

Why do we have this?

https://github.com/bytedeck/bytedeck/blob/9bf9dcd06f756b2fd97ada480887cb632ec0e50a/src/tenant/tests/test_admin.py#L61-L66

2022-01-28 18:12 UTC, tylerecouture commented
> 
> Why do we have this?
> 
> https://github.com/bytedeck/bytedeck/blob/9bf9dcd06f756b2fd97ada480887cb632ec0e50a/src/tenant/tests/test_admin.py#L61-L66

I don't remember! It looks like I was trying to test something bigger and couldn't get it to work so most of it is commented out.

2022-01-29 12:15 UTC, yujinyuz commented
Okay. I've finally understood why this was getting an error.

TL;DR: It is working for `v3.4.0`. In `v3.4.1`, they allowed schema names with special characters.


 This line in our test case:

https://github.com/bytedeck/bytedeck/blob/9bf9dcd06f756b2fd97ada480887cb632ec0e50a/src/tenant/tests/test_admin.py#L99-L105

It raises a `ValidationError` not because it has an invalid name, but because it has an invalid schema name. 

```
django.core.exceptions.ValidationError: ['Invalid string used for the schema name.']
```

And because `non public` schema name is now allowed in version `3.4.1`, it doesn't raise that error anymore.

Should we comment out the test first and look for a fix later?

2022-01-29 15:56 UTC, tylerecouture commented
I think the problem is that when creating a new tenant, we use the name to generate the schema and domain.

2022-01-30 02:47 UTC, yujinyuz commented
Btw, we already have tests for `TenantAdminForm` which is what I think should be tested instead of `save_model`.

> I think the problem is that when creating a new tenant, we use the name to generate the schema and domain.


Then what should be addressed should we use to generate the schema name and domain?

2022-01-30 04:47 UTC, tylerecouture commented
What about :8000/decks/new?

Will that form still work too? I don't remember if it's covered by tests.

2022-01-30 08:51 UTC, yujinyuz commented
@tylerecouture I just checked and it isn't covered by tests.

Apparently, we have `TenantForm` and `TenantAdminForm`

2022-01-30 17:12 UTC, tylerecouture commented
What's your suggestion?  Can you just manually test that view and if it's working fine (enter some bad names) carry on?  or can you write some tests for it?

2022-02-08 02:34 UTC, tylerecouture requested changes

2022-02-08 02:34 UTC, tylerecouture commented on requirements-production.txt
> +Django>=3.2,<4
@yujinyuz my comment here needs to be addressed in this PR Thanks!

2022-02-13 02:00 UTC, merged