rounded campaign icons to match every other icon on the website; clos…
bytedeck/bytedeck pull request #980
Opened 2022-05-27 01:54 UTC by Dylan-RG-Patterson

…es #976
![image](https://user-images.githubusercontent.com/105619909/170612945-49f77293-8f9f-4867-a024-4641b5e68296.png)

2022-05-27 02:17 UTC, tylerecouture requested changes
See inline comments

2022-05-27 02:17 UTC, tylerecouture commented on src/quest_manager/templates/quest_manager/category_list.html
> +    <td>{% if object.icon %}<img class="img-responsive panel-title-img img-rounded" src="{{ object.icon.url }}" width="50" height="50">{% endif %}</td>
What does "panel-title-img" do here?  I think that css sets the image size, but we've already hard coded the image size on this line.... hmm. 

I think we can use the panel-title-img class and remove the width and height attributes?  We should be using css anyway and not hardcoding.

2022-05-27 05:07 UTC, tylerecouture commented
@Dylan-RG-Patterson there's no test, which is fine since none of the other initialization stuff is tested... but can you verify that you've manually tested it by creating a new tenant and checking these new defaults show up?  Thanks!

2022-06-01 02:23 UTC, Dylan-RG-Patterson commented
hopefully this is what was in mind.

2022-06-01 03:06 UTC, merged