Added clarity to delete and revoke confirmation page, and added tooltip on revoke button; Closes #894
bytedeck/bytedeck pull request #994
Opened 2022-05-28 02:33 UTC by 9921622

Made a hover-help text for the revoke button titled 'Revoke' but cant screenshot because it disappears every time I press a button (including my screenshot button). So just take my word for it

Revoke badge confirmation page:
![image](https://user-images.githubusercontent.com/39788517/170806311-4d642acb-8670-4e88-83b5-ac3bf4d4f1a9.png)
Delete badge confirmation page:
![image](https://user-images.githubusercontent.com/39788517/170806327-b4ffe8a4-c99d-42fc-b9be-3275a6056c55.png)

2022-05-28 05:54 UTC, tylerecouture requested changes
Good PR, but after seeing the changes I've provided precise text to put for each warning.

2022-05-28 05:54 UTC, tylerecouture commented on src/badges/templates/badges/assertion_confirm_delete.html
>    <div class="well">
Change to this: "Are you sure you want to revoke this badge from {{ object.user }}?"

2022-05-28 05:54 UTC, tylerecouture commented on src/badges/templates/badges/badge_confirm_delete.html
> +  <p>Are you sure you want to Delete this Achievement? All instances of "{{object.name}}" badge will be deleted. Therefore, this badge will be removed from all users.<p>
Change to "Are you sure you want to delete this badge? This badge will be removed from all users that have earned it.  This action is irreversible."

2022-05-30 23:28 UTC, 9921622 commented
Ok ive updated the pr with a new commit that includes the requested changes

2022-05-31 04:26 UTC, merged